"""setup inicial completo

Revision ID: c92d0da20f84
Revises: 
Create Date: 2026-04-15 23:23:59.279684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92d0da20f84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_cardapio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria', sa.Enum('PIZZA', 'BEBIDA', 'SOBREMESA', 'LANCHE', 'ACOMPANHAMENTO', 'OUTROS', name='categoriaenum'), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_cardapio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_cardapio_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_cardapio_nome'), ['nome'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=250), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'FINALIZADO', 'CANCELADO', name='statusenum'), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_snapshot', sa.String(length=100), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('imagem_url_snapshot', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=100), nullable=True),
    sa.Column('tamanho', sa.String(length=100), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('item_cardapio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_cardapio_id'], ['itens_cardapio.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedidos')
    op.drop_table('pedidos')
    op.drop_table('usuario')
    with op.batch_alter_table('itens_cardapio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_cardapio_nome'))
        batch_op.drop_index(batch_op.f('ix_itens_cardapio_categoria'))

    op.drop_table('itens_cardapio')
    # ### end Alembic commands ###
